### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by axelson** [mroth/exmoji#16]
Hi, just wanted to do a quick check on if you are planning to continue to maintain this library, would be nice to look into some of the issues and PR's.

**Comment by mroth** [comment]
Yes, this library is roughly maintained. As far as I'm aware, all of the current issues/PRs are waiting on responses from the OPs to my questions. Please feel free jump in on any particular issues you see as unmaintained so that they can come to resolution. Thanks!

**Comment by axelson** [comment]
Okay, thanks!
